### ISSUE TITLE
Canceled Hosting Adoption, but server was provisioned and dashboard doesn't allow edit DNS record automagically

### ISSUE THREAD

**Issue by ebonato** [is-a-dev/manage-site#126]
After PR registration was merged, I've double checked manage.is-a.dev. It allows domain changes (probably will do an PR automagically again), but also offered to create hosting... after click on create host, a confirmation about DNS changes  was made, but 've decided to not use hosting wright now, so canceled confirmation. An error was thrown about no DNS changes made, but dashboard now only offers options to manage files (net2ftp browsing - which is working after setting password on hosting settings) and hosting settings.
I've believe that code is not prepared for a not so decided user like I was...

**Comment by ebonato** [comment]
To avoid hosting registrations that will not be used, this confirmation
https://github.com/is-a-dev/register.is-a.dev/blob/f5fd2d80e510161fc62bf060181d0a5465104209/src/routes/domains/%5Bdomain%5D/%2Bpage.svelte#L107
Should be done before domain registration on host.is-a.dev

**Comment by wdhdev** [comment]
is-a.dev Hosting was shut down.
